# Generated by Django 5.2 on 2025-04-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_category_saved_news'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='saved_news',
        ),
        migrations.AddField(
            model_name='customuser',
            name='saved_news',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='news.news'),
        ),
    ]
